### ISSUE TITLE
weird looking Mars

### ISSUE THREAD

**Issue by ProximaCentauri-star** [BananaMan9572/RSSVEVolumetricClouds#10]
Cause: Mars-Cirrus 2d cloud layer
![image](https://user-images.githubusercontent.com/26027991/216846974-64b36054-2742-4817-9038-42d49ceec3c1.png)
![image](https://user-images.githubusercontent.com/26027991/216846983-86ffaf04-266c-486a-be08-20af95a459b5.png)
![image](https://user-images.githubusercontent.com/26027991/216846991-b44ec78a-643f-4c88-bf43-47c03e927183.png)
![image](https://user-images.githubusercontent.com/26027991/216847017-e9cfc392-ea57-46b2-8548-9edf77d56441.png)
you said it

**Comment by BananaMan9572** [comment]
This is fixed, I am releasing a bugfix later today.
